---
kind: pipeline
type: docker
name: default

workspace:
  base: /src
  path: /egg

steps:
- name: egg-build
  image: node
  commands:
    - pwd
    - ls
    - cp -r ./ /src/egg

trigger:
  branch:
  - master
  event:
  - push