---
kind: pipeline
type: docker
name: default

workspace:
  base: /root/drone
  path: src

steps:
- name: egg-build
  image: node
  volumes:
  - name: prod
    path: /root/drone/src
  commands:
    - pwd
    - git clone https://github.com/evont/TED.git .
    - ls

trigger:
  branch:
  - master
  event:
  - push

volumes:
- name: prod
  host:
    path: /root/drone/src