---
kind: pipeline
type: docker
name: default

workspace:
  base: /root/traefik/e
  path: egg_server

clone: 
  disabled: true

steps:
- name: egg-build
  image: node
  volumes:
  - name: prod
    path: /root/traefik
  commands:
    - pwd
    - rm -rf egg_server
    - git clone https://github.com/evont/TED.git egg_server
    - cd egg_server && npm i --production --registry=https://registry.npm.taobao.org && cd ../
    - docker-compose up -d
    - ls

trigger:
  branch:
  - master
  event:
  - push

volumes:
- name: prod
  host:
    path: /root/traefik/egg_server