---
kind: pipeline
type: docker
name: default

workspace:
  base: /drone/src
  path: /egg

steps:
- name: egg-build
  image: node
  volumes:
  - name: prod
    path: /drone/src/egg
  commands:
    - pwd
    - npm i --production --registry=https://registry.npm.taobao.org
    - ls

trigger:
  branch:
  - master
  event:
  - push

volumes:
- name: prod
  host:
    path: /var/lib/drone/src