---
kind: pipeline
type: docker
name: default

workspace:
  base: /root/traefik/e
  path: egg_server

clone: 
  disabled: true

steps:
- name: egg-build
  image: node
  volumes:
  - name: prod
    path: /root/traefik/egg_server
  commands:
    - pwd
    - git pull https://github.com/evont/TED.git master
    - cd ../ && docker-compose up -d
    - ls

trigger:
  branch:
  - master
  event:
  - push

volumes:
- name: prod
  host:
    path: /root/traefik/egg_server