---
kind: pipeline
name: default
type: docker

steps:
- name: build
  image: node:11.10.1
  commands:
    - npm i --production --registry=https://registry.npm.taobao.org
    - npm run start

trigger:
  branch:
  - master
  event:
  - push