---
kind: pipeline
type: docker
name: default

clone:
  disable: true
  
steps:
- name: egg-build
  image: node
  volumes:
  - name: prod
    path: /root/traefik/egg_server
  commands:
    - pwd
    - git clone https://github.com/evont/TED.git .
    - cd ../ && docker-compose up -d
    - ls

trigger:
  branch:
  - master
  event:
  - push

volumes:
- name: prod
  host:
    path: /root/traefik/egg_server