---
  kind: pipeline
  type: docker
  name: default
   
  steps:
    - name: frontend:
      image: node:11.10.1
      commands:
        - npm i --production --registry=https://registry.npm.taobao.org
        - npm run start
        - rm -rf node_module