---
kind: pipeline
type: docker
name: default


steps:
  - name: egg-docker
    image: plugins/docker
    settings: 
      username: DOCKER_USERNAME
      password: DOCKER_PASSWORD
      repo: egistry.cn-hangzhou.aliyuncs.com/nefelibata/egg:
      registry: registry.cn-hangzhou.aliyuncs.com
      auto_tag: true

trigger:
  branch:
    - master
  event:
    - push
