---
kind: pipeline
name: default
type: docker

steps:
- name: build
  image: node
  commands:
    - npm i --production --registry=https://registry.npm.taobao.org

trigger:
  branch:
  - master
  event:
  - push